[versions]
# Android core
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"

# Testing
junit = "4.13.2"
ext-junit = "1.1.5"
espresso = "3.5.1"

# USB Serial
usbserial = "6.1.0"

# Build plugins
android-application = "8.7.2"

room = "2.6.1"
lifecycle = "2.7.0"
room-common-jvm = "2.7.1"

[libraries]
# AndroidX libraries
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

# Testing libraries
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "ext-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

# USB Serial library
usbserial = { module = "com.github.felHR85:UsbSerial", version.ref = "usbserial" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "room-common-jvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }